
// ꄤꁨꌺ  ꐥ
// 东ꁭꅐ，东南ꇐꄸꉻ，南ꒈꂪ，西南ꑾꌋꈤ，西ꁮꐚ，西北ꈌꄸꉻ。北方ꒈꀑ，东北ꑚꌋꈤ，地下ꅉꃴ，天上ꃅꃴ， 
const {getLunar} = require("chinese-lunar-calendar");
const dayjs = require("./dayjs");
const ZODIAC=[
  {
    yw:'ꉌ',
    cn:'鼠',
    month:'七月：新秋、兰秋、兰月、瓜月'
  },
  {
    yw:'ꑛ',
    cn:'牛',
    month:'八月：仲秋、桂月、壮月、竹春'
  },
  {
    yw:'ꆿ',
    cn:'虎',
    month:'九月：暮商、季秋、菊月、朽月、阳月'
  },
  {
    yw:'ꄯꆪ',
    cn:'兔',
    month:'十月：初冬、开冬、露月、良月'
  },
  {
    yw:'ꇐ',
    cn:'龙',
    month:'十一月：仲冬、辜月、葭月、龙潜月'
  },
  {
    yw:'ꏂ',
    cn:'蛇',
    month:'十二月：腊月、季冬、残冬、冰月、严月、冬月'
  },
  {
    yw:'ꃅ',
    cn:'马',
    month:'一月：正月、端月、开岁、嘉月'
  },
  {
    yw:'ꑿ',
    cn:'羊',
    month:'二月：杏月、丽月、仲春、如月'
  },
  {
    yw:'ꑙ',
    cn:'猴',
    month:'三月：季月、晚春、暮春、蚕月'
  },
  {
    yw:'ꃬ',
    cn:'鸡',
    month:'四月：麦月、阴月、梅月、纯阳'
  },
  {
    yw:'ꈌ',
    cn:'狗',
    month:'五月：仲夏、榴月、蒲月、皋月'
  },
  {
    yw:'ꃮ',
    cn:'猪',
    month:'六月：季夏、暑月、焦月、荷月'
  }]
const Y_DAY=[
    {
      yw:'ꅂ1',
      cn:'初一',
      tb:['ꁭꅐ','东方'],
    },
    {
      yw:'ꅂ2',
      cn:'初二',
      tb:['ꇐꄸꉻ','东南'],
    },
    {
      yw:'ꅂ3',
      cn:'初三',
      tb:['ꒈꂪ','南方'],
    },
    {
      yw:'ꅂ4',
      cn:'初四',
      tb:['ꑾꌋꈤ','西南'],
    },
    {
      yw:'ꅂ5',
      cn:'初五',
      tb:['ꁮꐚ','西方'],
    },
    {
      yw:'ꅂ6',
      cn:'初六',
      tb:['ꈌꄸꉻ','西北'],
    },
    {
      yw:'ꅂ7',
      cn:'初七',
      tb:['ꒈꀑ','北方'],
    },
    {
      yw:'ꅂ8',
      cn:'初八',
      tb:['ꑚꌋꈤ','东北'],
    },
    {
      yw:'ꅂ9',
      cn:'初九',
      tb:['ꅉꃴ','地下'],
    },
    {
      yw:'ꅂ10',
      cn:'初十',
      tb:['ꃅꃴ','天上'], 
    },
    {
      yw:'ꅂ11',
      cn:'十一',
      tb:['ꁭꅐ','东方'],
    },
    {
      yw:'ꅂ12',
      cn:'十二',
      tb:['ꇐꄸꉻ','东南'],
    },
    {
      yw:'ꅂ13',
      cn:'十三',
      tb:['ꒈꂪ','南方'],
    },
    {
      yw:'ꅂ14',
      cn:'十四',
      tb:['ꑾꌋꈤ','西南'],
    },
    {
      yw:'ꅂ15',
      cn:'十五',
      tb:['ꁮꐚ','西方'],
    },
    {
      yw:'ꒉ1',
      cn:'十六',
      tb:['ꈌꄸꉻ','西北'],
    },
    {
      yw:'ꒉ2',
      cn:'十七',
      tb:['ꒈꀑ','北方'],
    },
    {
      yw:'ꒉ3',
      cn:'十八',
      tb:['ꑚꌋꈤ','东北'],
    },
    {
      yw:'ꒉ4',
      cn:'十九',
      tb:['ꅉꃴ','地下'],
    },
    {
      yw:'ꒉ5',
      cn:'二十',
      tb:['ꃅꃴ','天上'], 
    },
    {
      yw:'ꒉ6',
      cn:'廿一',
      tb:['ꁭꅐ','东方'],
    },
    {
      yw:'ꒉ7',
      cn:'廿二',
      tb:['ꇐꄸꉻ','东南'],
    },
    {
      yw:'ꒉ8',
      cn:'廿三',
      tb:['ꒈꂪ','南方'],
    },
    {
      yw:'ꒉ9',
      cn:'廿四',
      tb:['ꑾꌋꈤ','西南'],
    },
    {
      yw:'ꒉ10',
      cn:'廿五',
      tb:['ꁮꐚ','西方'],
    },
    {
      yw:'ꒉ11',
      cn:'廿六',
      tb:['ꈌꄸꉻ','西北'],
    },
    {
      yw:'ꒉ12',
      cn:'廿七',
      tb:['ꒈꀑ','北方'],
    },
    {
      yw:'ꒉ13',
      cn:'廿八',
      tb:['ꑚꌋꈤ','东北'],
    },
    {
      yw:'ꒉ14',
      cn:'廿九',
      tb:['ꅉꃴ','地下'],
    },
    {
      yw:'ꒉ15',
      cn:'三十',
      tb:['ꃅꃴ','天上'], 
    },
]
function getZodiacDay(date) {
  const DayDiff=dayjs(date).diff('2024-11-08','day')%12;
  const index=DayDiff < 0 ? 12 + DayDiff : DayDiff
  return {
    index,
    yw:ZODIAC[index].yw,
    cn:ZODIAC[index].cn
  } 
}
export  function getYiZuCalendar({year,month,day,date}) {
  const lunar= date ? 
  getLunar(date.split('-')[0],date.split('-')[1],date.split('-')[2]) 
  : getLunar(year,month,day);
  const index=lunar.lunarMonth < 7 ? lunar.lunarMonth+5 : lunar.lunarMonth-7
  const zodiac= getZodiacDay(date ? date: `${year}-${month}-${day}`)
  return {
    solarTerm:lunar.solarTerm,
    sound:[
      `/static/year/${ZODIAC.findIndex(i=>i.cn===lunar.zodiac)}.m4a`,
      `/static/month/${index}.m4a`,
      `/static/yinL/${lunar.lunarDate-1}.m4a`,
      `/static/day/${zodiac.index}.m4a`,
      `/static/tabo/${(lunar.lunarDate-1)%10}.m4a`
     ],
    year:[ZODIAC.find( i => lunar.zodiac === i.cn)?.yw,lunar.zodiac],
    month:[ZODIAC[index].yw,ZODIAC[index].cn],
    tb:Y_DAY[lunar.lunarDate-1].tb,
    day:[Y_DAY[lunar.lunarDate-1].yw,Y_DAY[lunar.lunarDate-1].cn],
    zodiacDay:[zodiac.yw,zodiac.cn],
  }
}